import { Router } from "express";

const router = Router();

const NIFTY_50 = [
  "RELIANCE", "TCS", "HDFCBANK", "BHARTIARTL", "ICICIBANK",
  "INFY", "SBIN", "HINDUNILVR", "ITC", "LT",
  "KOTAKBANK", "AXISBANK", "BAJFINANCE", "MARUTI", "SUNPHARMA",
  "WIPRO", "ULTRACEMCO", "NESTLEIND", "ASIANPAINT", "TITAN",
  "POWERGRID", "NTPC", "TECHM", "COALINDIA", "BAJAJFINSV",
  "HCLTECH", "ONGC", "TATAMOTORS", "ADANIENT", "TATASTEEL",
  "ADANIPORTS", "JSWSTEEL", "CIPLA", "HINDALCO", "DRREDDY",
  "DIVISLAB", "BAJAJ-AUTO", "EICHERMOT", "SHRIRAMFIN", "GRASIM",
  "TATACONSUM", "BEL", "BRITANNIA", "HEROMOTOCO", "INDUSINDBK",
  "APOLLOHOSP", "M&M", "VEDL", "SBILIFE", "HDFCLIFE",
];

const NIFTY_BANK = [
  "HDFCBANK", "ICICIBANK", "KOTAKBANK", "AXISBANK", "SBIN",
  "INDUSINDBK", "BANDHANBNK", "FEDERALBNK", "IDFCFIRSTB", "AUBANK",
  "PNB", "BANKBARODA",
];

const NIFTY_IT = [
  "TCS", "INFY", "WIPRO", "HCLTECH", "TECHM",
  "MPHASIS", "LTIM", "PERSISTENT", "COFORGE", "OFSS",
];

const NIFTY_PHARMA = [
  "SUNPHARMA", "CIPLA", "DRREDDY", "DIVISLAB", "BIOCON",
  "LUPIN", "TORNTPHARM", "AUROPHARMA", "ALKEM", "ABBOTINDIA",
];

const NIFTY_AUTO = [
  "MARUTI", "TATAMOTORS", "BAJAJ-AUTO", "EICHERMOT", "HEROMOTOCO",
  "M&M", "TVSMOTOR", "ASHOKLEY", "BALKRISIND", "BHARATFORG",
];

// Major liquid stocks from Nifty Smallcap 250
const NIFTY_SMALLCAP_250 = [
  "ABCAPITAL", "AARTIIND", "AJANTPHARM", "APOLLOTYRE", "ASTRAL",
  "AUROPHARMA", "AVANTIFEED", "BAJAJELEC", "BALRAMCHIN", "BSE",
  "CANFINHOME", "CDSL", "CENTURYPLY", "CESC", "DEEPAKFERT",
  "DELTACORP", "ELGIEQUIP", "EMAMILTD", "ESCORTS", "FINEORG",
  "GAEL", "GALAXYSURF", "GLAND", "GNFC", "GODREJIND",
  "GRANULES", "GRINDWELL", "GUJGAS", "HEG", "HINDCOPPER",
  "IDFC", "IIFL", "INDIAMART", "IRCTC", "JKCEMENT",
  "KANSAINER", "KALYANKJIL", "LATENTVIEW", "MANAPPURAM", "MAXHEALTH",
  "NATCOPHARM", "NBCC", "OLECTRA", "PAGEIND", "PCBL",
  "PIDILITIND", "POLYCAB", "RITES", "SAIL", "SCHAEFFLER",
  "SJVN", "SKFINDIA", "SUPREMEIND", "TATAPOWER", "TIINDIA",
  "TORNTPOWER", "TRIDENT", "VBL", "VINATIORGA", "ZEEL",
  "NUVOCO", "HAPPSTMNDS", "ROUTE", "CLEAN", "INOXWIND",
  "WELSPUNLIV", "SUNTECK", "TATAINVEST", "JAYNECOIND", "PTCIL",
];

// Major liquid stocks from Nifty Microcap 250
const NIFTY_MICROCAP_250 = [
  "AIAENG", "AMBER", "ANANTRAJ", "APEX", "APCOTEXIND",
  "ARVINDFASN", "ATGL", "BARBEQUE", "BEPL", "BIKAJI",
  "BOROLTD", "CAPACITE", "CEATLTD", "CEREBROINT", "CHEMBOND",
  "CLEAN", "CONFIPET", "DATAMATICS", "DCAL", "DELHIVERY",
  "DHANI", "DHAMPUR", "DIAMONDYD", "DOLAT", "DPWORLDIL",
  "EASEMYTRIP", "ELECON", "ELGIEQUIP", "EPL", "EQUITASBNK",
  "ESFINANCE", "ETHOS", "FIEMIND", "FLAIR", "FLFL",
  "GALAXY", "GICRE", "GIPCL", "GMMPFAUDLR", "GPIL",
  "HARSHA", "HFCL", "HINDWAREAP", "HLEGLAS", "IDEAFORGE",
  "IFBIND", "IMAGICAA", "INDIGOPNTS", "INNOVACAP", "INOXGREEN",
  "JASH", "JAYAGROGN", "JBMA", "JIMMILAB", "JINDALSAW",
  "JKLAKSHMI", "JKPAPER", "JLHL", "JTLIND", "JUSTDIAL",
  "KALPATPOWR", "KFINTECH", "KIRIINDUS", "KRBL", "KSB",
  "LAXMIMACH", "LEMONTREE", "LLOYDMETAL", "LUXIND", "MAZDOCK",
];

router.get("/presets", (_req, res) => {
  res.json({
    presets: [
      { name: "Nifty 50", symbols: NIFTY_50 },
      { name: "Nifty Auto", symbols: NIFTY_AUTO },
      { name: "Nifty Smallcap 250", symbols: NIFTY_SMALLCAP_250 },
      { name: "Nifty Microcap 250", symbols: NIFTY_MICROCAP_250 },
    ],
  });
});

export default router;
